In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr=LogisticRegression()
lr.fit(X_train, Y_train)
lr.score(X_test, Y_test)

C:\Users\Mujtaba Jafri\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [4]:
svm=SVC()
svm.fit(X_train, Y_train)
svm.score(X_test, Y_test)

0.987037037037037

In [5]:
rf=RandomForestClassifier()
rf.fit(X_train, Y_train)
rf.score(X_test, Y_test)

0.9722222222222222

In [6]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test, Y_test)

In [9]:
get_score(SVC(), X_train, X_test, Y_train, Y_test)

0.987037037037037

In [10]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [14]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(),digits.data, digits.target)

C:\Users\Mujtaba Jafri\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mujtaba Jafri\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/m

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [17]:
cross_val_score(SVC(),digits.data, digits.target)


array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [18]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)


array([0.925     , 0.91944444, 0.94986072, 0.95821727, 0.93314763])