In [18]:
import pandas as pd
import numpy as np

df=pd.read_csv("homeprices.csv")

In [19]:
dummies=pd.get_dummies(df.town)
dummies.head(3)

monroe township  robinsville  west windsor
0             True        False         False
1             True        False         False
2             True        False         False

In [20]:
merged = pd.concat([df,dummies], axis='columns')

In [21]:
merged.head(2)

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000             True        False         False
1  monroe township  3000  565000             True        False         False

In [22]:
final=merged.drop(columns=['town','west windsor'])

In [23]:
final.head(2)

area   price  monroe township  robinsville
0  2600  550000             True        False
1  3000  565000             True        False

In [25]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [30]:
X=final.drop(columns="price")
X.head()

area  monroe township  robinsville
0  2600             True        False
1  3000             True        False
2  3200             True        False
3  3600             True        False
4  4000             True        False

In [32]:
y=final.price
y.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [33]:
model.fit(X,y)

LinearRegression()

In [34]:
model.predict([[2800,0,1]])

C:\Users\Mujtaba Jafri\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [36]:
model.predict([[3400,0,0]])

C:\Users\Mujtaba Jafri\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [37]:
model.score(X,y)

0.9573929037221872

In [54]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [55]:
dfle=df
dfle.town=le.fit_transform(dfle.town)

In [56]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [53]:
X= dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [45]:
y=dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [46]:
from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder(categorical_features=[0])

In [47]:
X=ohe.fit_transform(X).toarray()
X

array([[1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [49]:
X=X[:,1:]
X

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [50]:
model.fit(X,y)

LinearRegression()

In [52]:
model.predict([[1,0,2800]])

ValueError: X has 3 features, but LinearRegression is expecting 10 features as input.